defaults:
  - _self_
  - agent: potil
  - suite: dmc
  - override hydra/launcher: submitit_local

# Root Dir
root_dir: '/root/ROT2'

# replay buffer
replay_buffer_size: 500000
replay_buffer_num_workers: 2
nstep: 3
batch_size: 256 # 128
bz_ratio: 2
# misc
seed: 2
device_id: 0
device: cuda:${device_id}
save_video: false
save_train_video: false
use_tb: true

# experiment
obs_type: 'pixels' # pixels, features
experiment: ${agent.name}_${suite.name}_${obs_type}_${task_name}_seed_${seed}

# expert dataset
num_demos: 10 #50(openaigym), 10(dmc), 1(metaworld), 1(particle), 1(robotgym)
expert_dataset: '${root_dir}/ROT/expert_demos/${suite.name}/${task_name}/expert_demos.pkl'

# Load weights
load_bc: false

# Weights
bc_weight: '${root_dir}/ROT/weights/${suite.name}_${obs_type}/${task_name}/bc.pt'

# load snapshot
snap_name: 'snapshot_10.pt'
work_dir: default #'${root_dir}/ROT/exp_local/2022.09.19/115323_pc_v27_dmc_v27_features_walker_run_seed_3'

# Train with BC loss
bc_regularize: false
bc_weight_type: 'qfilter' # linear, qfilter

remark: default
exp_name: ${suite.name}_${agent.name}_${obs_type}_${task_name}_${remark}


hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}
  sweep:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}
    subdir: ${hydra.job.num}
  launcher:
    tasks_per_node: 1
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}/.slurm
